{
 "PRed": [
  {
   "PR": {
    "labels": [],
    "number": 1,
    "state": "closed"
   },
   "data": {
    "bot_rerun": false,
    "migrator_name": "NoarchPythonMinMigrator",
    "migrator_version": 1,
    "name": "noarch_python_min"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_version",
    "name"
   ]
  }
 ],
 "bad": {
  "exception": "Error running git command: CalledProcessError(1, ['git', 'push', 'https://github.com/regro-cf-autotick-bot/nirtorch-feedstock.git', '2.0_h1e7aa7'])",
  "traceback": [
   "Traceback (most recent call last):",
   "  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/git_utils.py\", line 207, in _run_git_command",
   "    p = subprocess.run(",
   "        ^^^^^^^^^^^^^^^",
   "  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.11/subprocess.py\", line 571, in run",
   "    raise CalledProcessError(retcode, process.args,",
   "subprocess.CalledProcessError: Command '['git', 'push', 'https://github.com/regro-cf-autotick-bot/nirtorch-feedstock.git', '2.0_h1e7aa7']' returned non-zero exit status 1.",
   "",
   "During handling of the above exception, another exception occurred:",
   "",
   "Traceback (most recent call last):",
   "  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py\", line 744, in _run_migrator_on_feedstock_branch",
   "    migrator_uid, pr_json = run_with_tmpdir(",
   "                            ^^^^^^^^^^^^^^^^",
   "  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py\", line 451, in run_with_tmpdir",
   "    return run(",
   "           ^^^^",
   "  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py\", line 619, in run",
   "    git_backend.push_to_repository(",
   "  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.11/contextlib.py\", line 81, in inner",
   "    return func(*args, **kwds)",
   "           ^^^^^^^^^^^^^^^^^^^",
   "  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/git_utils.py\", line 838, in push_to_repository",
   "    self.cli.push_to_url(git_dir, remote_url, branch)",
   "  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.11/contextlib.py\", line 81, in inner",
   "    return func(*args, **kwds)",
   "           ^^^^^^^^^^^^^^^^^^^",
   "  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/git_utils.py\", line 300, in push_to_url",
   "    self._run_git_command([\"push\", remote_url, branch], git_dir)",
   "  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.11/contextlib.py\", line 81, in inner",
   "    return func(*args, **kwds)",
   "           ^^^^^^^^^^^^^^^^^^^",
   "  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/git_utils.py\", line 219, in _run_git_command",
   "    raise GitCliError(f\"Error running git command: {repr(e)}\")",
   "conda_forge_tick.git_utils.GitCliError: Error running git command: CalledProcessError(1, ['git', 'push', 'https://github.com/regro-cf-autotick-bot/nirtorch-feedstock.git', '2.0_h1e7aa7'])",
   ""
  ]
 },
 "pinning_version": "2024.12.21.10.18.30",
 "pre_pr_migrator_attempts": {},
 "pre_pr_migrator_status": {},
 "smithy_version": "3.45.1"
}