{
 "PRed": [
  {
   "PR": {
    "number": 1,
    "state": "closed"
   },
   "data": {
    "bot_rerun": false,
    "migrator_name": "Version",
    "migrator_version": 0,
    "version": "0.2.12"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_version",
    "version"
   ]
  },
  {
   "PR": {
    "__lazy_json__": "pr_json/2158955881.json"
   },
   "data": {
    "bot_rerun": false,
    "migrator_name": "Version",
    "migrator_version": 0,
    "version": "0.2.13"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_version",
    "version"
   ]
  }
 ],
 "bad": false,
 "pinning_version": "2024.11.01.21.49.52",
 "pre_pr_migrator_attempts": {
  "noarch_python_min": 9
 },
 "pre_pr_migrator_status": {
  "noarch_python_min": "bot error (<a href=\"https://github.com/regro/cf-scripts/actions/runs/12982525137\">bot CI job</a>): main:\nTraceback (most recent call last):\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_forge_feedstock_ops/__main__.py\", line 104, in _run_bot_task\n    data = func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_forge_feedstock_ops/__main__.py\", line 216, in _rerender_feedstock\n    msg = rerender_local(fs_dir, **kwargs)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_forge_feedstock_ops/rerender.py\", line 255, in rerender_local\n    raise RuntimeError(f\"Failed to rerender.\noutput: {ret.stdout}\n\")\nRuntimeError: Failed to rerender.\noutput: Traceback (most recent call last):\n  File \"/opt/conda/envs/cf-scripts/bin/conda-smithy\", line 10, in <module>\n    sys.exit(main())\n             ^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/cli.py\", line 767, in main\n    args.subcommand_func(args)\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/cli.py\", line 610, in __call__\n    self._call(args, args.temporary_directory)\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/cli.py\", line 613, in _call\n    configure_feedstock.main(\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/configure_feedstock.py\", line 2858, in main\n    exclusive_config_file, cf_pinning_ver = get_cached_cfp_file_path(\n                                            ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/configure_feedstock.py\", line 2678, in get_cached_cfp_file_path\n    get_cfp_file_path(smithy_cache)\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/configure_feedstock.py\", line 2602, in get_cfp_file_path\n    pkg = get_most_recent_version(\"conda-forge-pinning\")\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/configure_feedstock.py\", line 2544, in get_most_recent_version\n    request.raise_for_status()\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/requests/models.py\", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 524 Server Error:  for url: https://api.anaconda.org/package/conda-forge/conda-forge-pinning\n\n\n"
 },
 "smithy_version": "3.43.2"
}