{
 "bad": false,
 "new_version": "0.51b0",
 "new_version_attempts": {
  "0.24b0": 3.8000000000000007,
  "0.25b0": 3.2,
  "0.25b1": 0.7999999999999998,
  "0.25b2": 3.8000000000000016,
  "0.26b1": 1.4,
  "0.27b0": 1.5999999999999999,
  "0.28b0": 1.9999999999999998,
  "0.28b1": 1.5999999999999999,
  "0.29b0": 2.3999999999999995,
  "0.29b1": 1,
  "0.30b0": 1.7999999999999998,
  "0.30b1": 1.7999999999999998,
  "0.31b0": 1.5999999999999999,
  "0.32b0": 1.5999999999999999,
  "0.33b0": 1.7999999999999998,
  "0.34b0": 25,
  "0.35b0": 4,
  "0.36b0": 3,
  "0.37b0": 1.4,
  "0.38b0": 1.4,
  "0.39b0": 1.5999999999999999,
  "0.40b0": 1.4,
  "0.41b0": 1.4,
  "0.42b0": 4.000000000000001,
  "0.43b0": 1,
  "0.44b0": 1.4,
  "0.45b0": 2.8000000000000007,
  "0.51b0": 1.4
 },
 "new_version_errors": {
  "0.24b0": "not solvable (<a href=\"https://github.com/regro/autotick-bot/actions/runs/1243851780\">bot CI job</a>): master: ['linux_64_: Encountered problems while solving:\\n  - nothing provides requested opentelemetry-instrumentation-wsgi 0.24b0.*\\n']",
  "0.25b0": "not solvable (<a href=\"https://github.com/regro/autotick-bot/actions/runs/1350867159\">bot CI job</a>): master: ['linux_64_: Encountered problems while solving:\\n  - nothing provides requested opentelemetry-instrumentation-wsgi 0.25b0.*\\n  - package opentelemetry-util-http-0.25b0-pyhd8ed1ab_0 requires opentelemetry-instrumentation 0.24b0, but none of the providers can be installed\\n']",
  "0.25b1": "not solvable (<a href=\"https://github.com/regro/autotick-bot/actions/runs/1359927877\">bot CI job</a>): master: ['linux_64_: Encountered problems while solving:\\n  - nothing provides requested opentelemetry-util-http 0.25b1.*\\n  - nothing provides requested opentelemetry-instrumentation-wsgi 0.25b1.*\\n']",
  "0.25b2": "not solvable (<a href=\"https://github.com/regro/autotick-bot/actions/runs/1448448835\">bot CI job</a>): master: ['linux_64_: Encountered problems while solving:\\n  - nothing provides requested opentelemetry-instrumentation-wsgi 0.25b2.*\\n  - package opentelemetry-util-http-0.25b2-pyhd8ed1ab_0 requires opentelemetry-instrumentation 0.24b0, but none of the providers can be installed\\n']",
  "0.26b1": "not solvable (<a href=\"https://github.com/regro/autotick-bot/actions/runs/1452209147\">bot CI job</a>): master: ['linux_64_: Encountered problems while solving:\\n  - nothing provides requested opentelemetry-instrumentation-wsgi 0.26b1.*\\n']",
  "0.27b0": "not solvable (<a href=\"https://github.com/regro/autotick-bot/actions/runs/1594851977\">bot CI job</a>): master: ['linux_64_: Encountered problems while solving:\\n  - nothing provides requested opentelemetry-instrumentation-wsgi 0.27b0.*\\n']",
  "0.28b0": "not solvable (<a href=\"https://github.com/regro/autotick-bot/actions/runs/1756662635\">bot CI job</a>): master: ['MemoryError()']",
  "0.28b1": "not solvable (<a href=\"https://github.com/regro/autotick-bot/actions/runs/1774294642\">bot CI job</a>): master: ['linux_64_: Encountered problems while solving:\\n  - nothing provides requested opentelemetry-instrumentation-wsgi 0.28b1.*\\n']",
  "0.29b0": "not solvable (<a href=\"https://github.com/regro/autotick-bot/actions/runs/1971651394\">bot CI job</a>): master: ['linux_64_: Encountered problems while solving:\\n  - nothing provides requested opentelemetry-instrumentation-wsgi 0.29b0.*\\n']",
  "0.30b0": "not solvable (<a href=\"https://github.com/regro/autotick-bot/actions/runs/2187604854\">bot CI job</a>): main: ['linux_64_: Encountered problems while solving:\\n  - nothing provides requested opentelemetry-instrumentation-wsgi 0.30b0.*\\n']",
  "0.30b1": "not solvable (<a href=\"https://github.com/regro/autotick-bot/actions/runs/2206020323\">bot CI job</a>): main: ['linux_64_: Encountered problems while solving:\\n  - nothing provides requested opentelemetry-instrumentation-wsgi 0.30b1.*\\n']",
  "0.31b0": "not solvable (<a href=\"https://github.com/regro/autotick-bot/actions/runs/2344673865\">bot CI job</a>): main: ['linux_64_: Encountered problems while solving:\\n  - nothing provides requested opentelemetry-instrumentation-wsgi 0.31b0.*\\n']",
  "0.32b0": "not solvable (<a href=\"https://github.com/regro/autotick-bot/actions/runs/2612811657\">bot CI job</a>): main: ['linux_64_: Encountered problems while solving:\\n  - nothing provides requested opentelemetry-instrumentation-wsgi 0.32b0.*\\n']",
  "0.33b0": "not solvable (<a href=\"https://github.com/regro/autotick-bot/actions/runs/2831890097\">bot CI job</a>): main: ['linux_64_: Encountered problems while solving:\\n  - nothing provides requested opentelemetry-instrumentation-wsgi 0.33b0.*\\n']",
  "0.34b0": "The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '0.34b0' to make sure they exist!\n\nWe also found the following errors:\n\n - could not hash URL template 'https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry-instrumentation-flask-{{ version }}.tar.gz'\n",
  "0.35b0": "The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '0.35b0' to make sure they exist!\n\nWe also found the following errors:\n\n - could not hash URL template 'https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry-instrumentation-flask-{{ version }}.tar.gz'\n",
  "0.36b0": "The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '0.36b0' to make sure they exist!\n\nWe also found the following errors:\n\n - could not hash URL template 'https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry-instrumentation-flask-{{ version }}.tar.gz'\n",
  "0.37b0": "not solvable (<a href=\"https://github.com/regro/autotick-bot/actions/runs/4210603502\">bot CI job</a>): main: ['linux_64_: Encountered problems while solving:\\n  - nothing provides requested opentelemetry-instrumentation-wsgi 0.37b0.*\\n']",
  "0.38b0": "not solvable (<a href=\"https://github.com/regro/cf-scripts/actions/runs/4498715145\">bot CI job</a>): main: ['linux_64_: Encountered problems while solving:\\n  - nothing provides requested opentelemetry-util-http 0.38b0.*\\n  - nothing provides requested opentelemetry-instrumentation-wsgi 0.38b0.*\\n']",
  "0.39b0": "not solvable (<a href=\"https://github.com/regro/cf-scripts/actions/runs/5030408474\">bot CI job</a>): main: ['linux_64_: Encountered problems while solving:\\n  - nothing provides requested opentelemetry-instrumentation-wsgi 0.39b0.*\\n']",
  "0.40b0": "not solvable (<a href=\"https://github.com/regro/cf-scripts/actions/runs/5549565068\">bot CI job</a>): main: ['linux_64_: Encountered problems while solving:\\n  - nothing provides requested opentelemetry-instrumentation 0.40b0.*  - nothing provides requested opentelemetry-instrumentation-wsgi 0.40b0.*  - nothing provides requested opentelemetry-util-http 0.40b0.*']",
  "0.41b0": "not solvable (<a href=\"https://github.com/regro/cf-scripts/actions/runs/6167470756\">bot CI job</a>): main: ['linux_64_: Encountered problems while solving:\\n  - nothing provides requested opentelemetry-instrumentation-wsgi 0.41b0.*\\n']",
  "0.42b0": "not solvable (<a href='https://github.com/regro/cf-scripts/actions/runs/6840426293'>bot CI job</a>) @ main\n                <details>\n                <div align=\"left\">\n                <pre>\n                linux_64_: Could not solve for environment specs\nThe following packages are incompatible\n\u251C\u2500 opentelemetry-instrumentation-wsgi 0.42b0.*  does not exist (perhaps a typo or a missing channel);\n\u2514\u2500 opentelemetry-semantic-conventions 0.42b0.*  does not exist (perhaps a typo or a missing channel).\n                </pre>\n                </div>\n                </details>",
  "0.44b0": "not solvable (<a href='https://github.com/regro/cf-scripts/actions/runs/8028967281'>bot CI job</a>) @ main\n                <details>\n                <div align=\"left\">\n                <pre>\n                linux_64_: Could not solve for environment specs\nThe following package could not be installed\n\u2514\u2500 opentelemetry-instrumentation-wsgi 0.44b0.*  does not exist (perhaps a typo or a missing channel).\n                </pre>\n                </div>\n                </details>",
  "0.45b0": "not solvable (<a href='https://github.com/regro/cf-scripts/actions/runs/8478450636'>bot CI job</a>) @ main\n                <details>\n                <div align=\"left\">\n                <pre>\n                linux_64_: Could not solve for environment specs\nThe following packages are incompatible\n\u251C\u2500 opentelemetry-instrumentation-wsgi 0.45b0.*  does not exist (perhaps a typo or a missing channel);\n\u2514\u2500 opentelemetry-semantic-conventions 0.45b0.*  does not exist (perhaps a typo or a missing channel).\n                </pre>\n                </div>\n                </details>",
  "0.51b0": "bot error (<a href=\"https://github.com/regro/cf-scripts/actions/runs/13145184227\">bot CI job</a>): main:\nTraceback (most recent call last):\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_forge_feedstock_ops/__main__.py\", line 104, in _run_bot_task\n    data = func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_forge_feedstock_ops/__main__.py\", line 216, in _rerender_feedstock\n    msg = rerender_local(fs_dir, **kwargs)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_forge_feedstock_ops/rerender.py\", line 255, in rerender_local\n    raise RuntimeError(f\"Failed to rerender.\noutput: {ret.stdout}\n\")\nRuntimeError: Failed to rerender.\noutput: INFO:conda_smithy.configure_feedstock:Downloading conda-forge-pinning-2025.02.04.19.34.29\nTraceback (most recent call last):\n  File \"/opt/conda/envs/cf-scripts/bin/conda-smithy\", line 10, in <module>\n    sys.exit(main())\n             ^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/cli.py\", line 767, in main\n    args.subcommand_func(args)\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/cli.py\", line 610, in __call__\n    self._call(args, args.temporary_directory)\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/cli.py\", line 613, in _call\n    configure_feedstock.main(\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/configure_feedstock.py\", line 2858, in main\n    exclusive_config_file, cf_pinning_ver = get_cached_cfp_file_path(\n                                            ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/configure_feedstock.py\", line 2678, in get_cached_cfp_file_path\n    get_cfp_file_path(smithy_cache)\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/configure_feedstock.py\", line 2619, in get_cfp_file_path\n    response.raise_for_status()\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/requests/models.py\", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 520 Server Error:  for url: https://api.anaconda.org/download/conda-forge/conda-forge-pinning/2025.02.04.19.34.29/noarch/conda-forge-pinning-2025.02.04.19.34.29-hd8ed1ab_0.conda\n\n\n"
 }
}