{
 "PRed": [
  {
   "data": {
    "bot_rerun": false,
    "migrator_name": "CompilerRebuild",
    "migrator_version": 1,
    "name": "Python 3.7, GCC 7, R 3.5.1, openBLAS 0.3.2"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_version",
    "name"
   ]
  }
 ],
 "bad": {
  "exception": "Error running 'conda-forge-tick-container migrate-feedstock --feedstock-name nginx-module-njs --default-branch main --existing-feedstock-node-attrs - --log-level info --kwargs {\n \"hash_type\": \"sha256\"\n}' in container - error UnboundLocalError raised:\n\"cannot access local variable 'url' where it is not associated with a value\"",
  "traceback": [
   "Traceback (most recent call last):",
   "  File \"/opt/autotick-bot/conda_forge_tick/container_cli.py\", line 119, in _run_bot_task",
   "    data = func(attrs=attrs, **kwargs)",
   "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^",
   "  File \"/opt/autotick-bot/conda_forge_tick/container_cli.py\", line 225, in _migrate_feedstock",
   "    data = run_migration_local(",
   "           ^^^^^^^^^^^^^^^^^^^^",
   "  File \"/opt/autotick-bot/conda_forge_tick/migration_runner.py\", line 251, in run_migration_local",
   "    data[\"migrate_return_value\"] = migrator.migrate(",
   "                                   ^^^^^^^^^^^^^^^^^",
   "  File \"/opt/autotick-bot/conda_forge_tick/migrators/version.py\", line 230, in migrate",
   "    updated_meta_yaml, errors = update_version(",
   "                                ^^^^^^^^^^^^^^^",
   "  File \"/opt/autotick-bot/conda_forge_tick/update_recipe/version.py\", line 880, in update_version",
   "    _did_update, _errors = _try_to_update_version(",
   "                           ^^^^^^^^^^^^^^^^^^^^^^^",
   "  File \"/opt/autotick-bot/conda_forge_tick/update_recipe/version.py\", line 516, in _try_to_update_version",
   "    new_url_tmpl, new_hash = _get_new_url_tmpl_and_hash(",
   "                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^",
   "  File \"/opt/autotick-bot/conda_forge_tick/update_recipe/version.py\", line 312, in _get_new_url_tmpl_and_hash",
   "    if url != url_tmpl:",
   "       ^^^",
   "UnboundLocalError: cannot access local variable 'url' where it is not associated with a value",
   ""
  ]
 },
 "pinning_version": "2019.01.29",
 "pre_pr_migrator_attempts": {
  "version": 1
 },
 "pre_pr_migrator_status": {
  "version": "bot error: master: Traceback (most recent call last):\n  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/git_utils.py\", line 135, in fetch_repo\n    _run_git_cmd(f\"git checkout --track upstream/{base_branch} {quiet}\")\n  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/git_utils.py\", line 121, in _run_git_cmd\n    return subprocess.run(cmd, shell=True, check=True)\n  File \"/usr/share/miniconda/envs/run_env/lib/python3.8/subprocess.py\", line 512, in run\n    raise CalledProcessError(retcode, process.args,\nsubprocess.CalledProcessError: Command 'git checkout --track upstream/master --quiet' returned non-zero exit status 128.\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/auto_tick.py\", line 1018, in main\n    migrator_uid, pr_json = run(\n  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/auto_tick.py\", line 163, in run\n    feedstock_dir, repo = get_repo(\n  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/git_utils.py\", line 220, in get_repo\n    if fetch_repo(\n  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/git_utils.py\", line 137, in fetch_repo\n    _run_git_cmd(\n  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/git_utils.py\", line 121, in _run_git_cmd\n    return subprocess.run(cmd, shell=True, check=True)\n  File \"/usr/share/miniconda/envs/run_env/lib/python3.8/subprocess.py\", line 512, in run\n    raise CalledProcessError(retcode, process.args,\nsubprocess.CalledProcessError: Command 'git checkout -b master upstream/master --quiet' returned non-zero exit status 128.\n"
 },
 "smithy_version": "3.2.12"
}