{
 "bad": false,
 "new_version": "3.9.0",
 "new_version_attempts": {
  "3.3.1": 1,
  "3.3.2": 1,
  "3.3.3": 1,
  "3.3.4": 1,
  "3.4.0": 1,
  "3.4.1": 1,
  "3.4.4": 1,
  "3.5.0": 1,
  "3.5.1": 1,
  "3.5.2": 1,
  "3.5.3": 1,
  "3.5.4": 1,
  "3.6.0": 1,
  "3.6.1": 1,
  "3.6.2": 1,
  "3.6.3": 1,
  "3.8.4": 1
 },
 "new_version_errors": {
  "3.8.4": "bot error (<a href=\"https://github.com/regro/cf-scripts/actions/runs/12122165236\">bot CI job</a>): main:\nTraceback (most recent call last):\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py\", line 740, in _run_migrator_on_feedstock_branch\n    migrator_uid, pr_json = run_with_tmpdir(\n                            ^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py\", line 454, in run_with_tmpdir\n    return run(\n           ^^^^\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py\", line 622, in run\n    _push_pr_json_via_gh_api(\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py\", line 716, in _push_pr_json_via_gh_api\n    repo = gh.repository(\"conda-forge\", \"cf-graph-countyfair\")\n           ^^^^^^^^^^^^^\nAttributeError: 'Github' object has no attribute 'repository'\n"
 }
}