{
 "PRed": [
  {
   "PR": {
    "head": {
     "ref": "<this_is_not_a_branch>"
    },
    "state": "closed"
   },
   "data": {
    "bot_rerun": false,
    "migrator_name": "ArchRebuild",
    "migrator_version": 1,
    "name": "aarch64 and ppc64le addition"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_version",
    "name"
   ]
  },
  {
   "PR": {
    "number": 2,
    "state": "closed"
   },
   "data": {
    "bot_rerun": false,
    "migrator_name": "OSXArm",
    "migrator_version": 1,
    "name": "arm osx addition"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_version",
    "name"
   ]
  },
  {
   "PR": {
    "number": 3,
    "state": "closed"
   },
   "data": {
    "bot_rerun": false,
    "migrator_name": "Version",
    "migrator_version": 0,
    "version": "2022.11"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_version",
    "version"
   ]
  },
  {
   "PR": {
    "number": 4,
    "state": "closed"
   },
   "data": {
    "bot_rerun": false,
    "migrator_name": "Version",
    "migrator_version": 0,
    "version": "2023.02"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_version",
    "version"
   ]
  },
  {
   "PR": {
    "labels": [],
    "number": 5,
    "state": "closed"
   },
   "data": {
    "bot_rerun": false,
    "migrator_name": "Version",
    "migrator_version": 0,
    "version": "2024.05"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_version",
    "version"
   ]
  }
 ],
 "bad": false,
 "pinning_version": "2024.05.24.03.56.36",
 "pre_pr_migrator_attempts": {
  "noarch_python_min": 5
 },
 "pre_pr_migrator_status": {
  "noarch_python_min": "bot error (<a href=\"https://github.com/regro/cf-scripts/actions/runs/12927235439\">bot CI job</a>): main:\nTraceback (most recent call last):\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda/models/version.py\", line 44, in __call__\n    return cls._cache_[arg]\n           ~~~~~~~~~~~^^^^^\nKeyError: '>='\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda/models/match_spec.py\", line 60, in __call__\n    return super().__call__(**parsed)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda/models/match_spec.py\", line 190, in __init__\n    self._match_components = self._build_components(**kwargs)\n                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda/models/match_spec.py\", line 425, in _build_components\n    return frozendict(_make_component(key, value) for key, value in kwargs.items())\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/frozendict/_frozendict_py.py\", line 59, in __new__\n    dict.__init__(self, *args, **kwargs)\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda/models/match_spec.py\", line 425, in <genexpr>\n    return frozendict(_make_component(key, value) for key, value in kwargs.items())\n                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda/models/match_spec.py\", line 439, in _make_component\n    matcher = _implementors[field_name](value)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda/models/version.py\", line 46, in __call__\n    val = cls._cache_[arg] = super().__call__(arg)\n                             ^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda/models/version.py\", line 523, in __init__\n    vspec_str, matcher, is_exact = self.get_matcher(vspec)\n                                   ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda/models/version.py\", line 552, in get_matcher\n    raise InvalidVersionSpec(vspec_str, \"invalid operator\")\nconda.exceptions.InvalidVersionSpec: Invalid version '>=': invalid operator\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_forge_feedstock_check_solvable/rattler_solver.py\", line 100, in solve\n    _specs = [MatchSpec(convert_spec_to_conda_build(s)) for s in specs]\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_forge_feedstock_check_solvable/rattler_solver.py\", line 100, in <listcomp>\n    _specs = [MatchSpec(convert_spec_to_conda_build(s)) for s in specs]\n                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_forge_feedstock_check_solvable/utils.py\", line 244, in convert_spec_to_conda_build\n    m = MatchSpec(myspec)\n        ^^^^^^^^^^^^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda/models/match_spec.py\", line 82, in __call__\n    raise InvalidMatchSpec(msg, details=e) from e\nconda.exceptions.InvalidMatchSpec: Invalid spec 'python >=': Invalid version '>=': invalid operator\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda/models/version.py\", line 44, in __call__\n    return cls._cache_[arg]\n           ~~~~~~~~~~~^^^^^\nKeyError: '>='\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda/models/match_spec.py\", line 60, in __call__\n    return super().__call__(**parsed)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda/models/match_spec.py\", line 190, in __init__\n    self._match_components = self._build_components(**kwargs)\n                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda/models/match_spec.py\", line 425, in _build_components\n    return frozendict(_make_component(key, value) for key, value in kwargs.items())\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/frozendict/_frozendict_py.py\", line 59, in __new__\n    dict.__init__(self, *args, **kwargs)\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda/models/match_spec.py\", line 425, in <genexpr>\n    return frozendict(_make_component(key, value) for key, value in kwargs.items())\n                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda/models/match_spec.py\", line 439, in _make_component\n    matcher = _implementors[field_name](value)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda/models/version.py\", line 46, in __call__\n    val = cls._cache_[arg] = super().__call__(arg)\n                             ^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda/models/version.py\", line 523, in __init__\n    vspec_str, matcher, is_exact = self.get_matcher(vspec)\n                                   ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda/models/version.py\", line 552, in get_matcher\n    raise InvalidVersionSpec(vspec_str, \"invalid operator\")\nconda.exceptions.InvalidVersionSpec: Invalid version '>=': invalid operator\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/opt/autotick-bot/conda_forge_tick/container_cli.py\", line 122, in _run_bot_task\n    data = func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"/opt/autotick-bot/conda_forge_tick/container_cli.py\", line 389, in _check_solvable\n    data[\"solvable\"], data[\"errors\"], data[\"solvable_by_variant\"] = is_recipe_solvable(\n                                                                    ^^^^^^^^^^^^^^^^^^^\n  File \"/opt/autotick-bot/conda_forge_tick/solver_checks.py\", line 91, in is_recipe_solvable\n    return _is_recipe_solvable(\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_forge_feedstock_check_solvable/check_solvable.py\", line 83, in is_recipe_solvable\n    res = _is_recipe_solvable(\n          ^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_forge_feedstock_check_solvable/check_solvable.py\", line 170, in _is_recipe_solvable\n    _solvable, _errors = _is_recipe_solvable_on_platform(\n                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_forge_feedstock_check_solvable/check_solvable.py\", line 429, in _is_recipe_solvable_on_platform\n    _solvable, _err, _ = solver.solve(\n                         ^^^^^^^^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_forge_feedstock_check_solvable/rattler_solver.py\", line 138, in solve\n    __specs = [convert_spec_to_conda_build(s) for s in specs]\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_forge_feedstock_check_solvable/rattler_solver.py\", line 138, in <listcomp>\n    __specs = [convert_spec_to_conda_build(s) for s in specs]\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_forge_feedstock_check_solvable/utils.py\", line 244, in convert_spec_to_conda_build\n    m = MatchSpec(myspec)\n        ^^^^^^^^^^^^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda/models/match_spec.py\", line 82, in __call__\n    raise InvalidMatchSpec(msg, details=e) from e\nconda.exceptions.InvalidMatchSpec: Invalid spec 'python >=': Invalid version '>=': invalid operator\n"
 },
 "smithy_version": "3.36.0"
}