{
 "PRed": [
  {
   "PR": {
    "labels": [],
    "number": 1,
    "state": "closed"
   },
   "data": {
    "bot_rerun": false,
    "migrator_name": "MigrationYaml",
    "migrator_object_version": 1,
    "migrator_version": 0,
    "name": "python312"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_object_version",
    "migrator_version",
    "name"
   ]
  },
  {
   "PR": {
    "labels": [],
    "number": null,
    "state": "closed"
   },
   "data": {
    "bot_rerun": false,
    "migrator_name": "MigrationYaml",
    "migrator_object_version": 1,
    "migrator_version": 0,
    "name": "hdf51142"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_object_version",
    "migrator_version",
    "name"
   ]
  },
  {
   "PR": {
    "labels": [
     {
      "name": "bot-rerun"
     }
    ],
    "number": 2,
    "state": "closed"
   },
   "data": {
    "bot_rerun": 1701706655.5983117,
    "migrator_name": "MigrationYaml",
    "migrator_object_version": 1,
    "migrator_version": 0,
    "name": "pypy38"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_object_version",
    "migrator_version",
    "name"
   ]
  },
  {
   "PR": {
    "labels": [
     {
      "name": "bot-rerun"
     }
    ],
    "number": 4,
    "state": "closed"
   },
   "data": {
    "bot_rerun": 1701464597.4251988,
    "migrator_name": "MigrationYaml",
    "migrator_object_version": 1,
    "migrator_version": 0,
    "name": "libxml2212"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_object_version",
    "migrator_version",
    "name"
   ]
  },
  {
   "PR": {
    "labels": [],
    "number": 6,
    "state": "closed"
   },
   "data": {
    "bot_rerun": false,
    "migrator_name": "MigrationYaml",
    "migrator_object_version": 1,
    "migrator_version": 0,
    "name": "libxml2212"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_object_version",
    "migrator_version",
    "name"
   ]
  },
  {
   "PR": {
    "labels": [
     {
      "name": "bot-rerun"
     }
    ],
    "number": 7,
    "state": "closed"
   },
   "data": {
    "bot_rerun": 1726002193.1954238,
    "migrator_name": "MigrationYaml",
    "migrator_object_version": 1,
    "migrator_version": 0,
    "name": "pypy38"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_object_version",
    "migrator_version",
    "name"
   ]
  },
  {
   "PR": {
    "labels": [],
    "number": 8,
    "state": "closed"
   },
   "data": {
    "bot_rerun": false,
    "migrator_name": "MigrationYaml",
    "migrator_object_version": 1,
    "migrator_version": 0,
    "name": "python313"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_object_version",
    "migrator_version",
    "name"
   ]
  },
  {
   "PR": {
    "labels": [],
    "number": 11,
    "state": "closed"
   },
   "data": {
    "bot_rerun": false,
    "migrator_name": "MigrationYaml",
    "migrator_object_version": 1,
    "migrator_version": 0,
    "name": "hdf51144"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_object_version",
    "migrator_version",
    "name"
   ]
  },
  {
   "PR": {
    "labels": [],
    "number": 12,
    "state": "closed"
   },
   "data": {
    "bot_rerun": false,
    "migrator_name": "MigrationYaml",
    "migrator_object_version": 2,
    "migrator_version": 0,
    "name": "hdf51144"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_object_version",
    "migrator_version",
    "name"
   ]
  }
 ],
 "bad": {
  "exception": "<class 'requests.exceptions.ConnectionError'>: A connection-level exception occurred: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))",
  "traceback": [
   "Traceback (most recent call last):",
   "  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 715, in urlopen",
   "    httplib_response = self._make_request(",
   "                       ^^^^^^^^^^^^^^^^^^^",
   "  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 467, in _make_request",
   "    six.raise_from(e, None)",
   "  File \"<string>\", line 3, in raise_from",
   "  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 462, in _make_request",
   "    httplib_response = conn.getresponse()",
   "                       ^^^^^^^^^^^^^^^^^^",
   "  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.11/http/client.py\", line 1395, in getresponse",
   "    response.begin()",
   "  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.11/http/client.py\", line 325, in begin",
   "    version, status, reason = self._read_status()",
   "                              ^^^^^^^^^^^^^^^^^^^",
   "  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.11/http/client.py\", line 294, in _read_status",
   "    raise RemoteDisconnected(\"Remote end closed connection without\"",
   "http.client.RemoteDisconnected: Remote end closed connection without response",
   "",
   "During handling of the above exception, another exception occurred:",
   "",
   "Traceback (most recent call last):",
   "  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.11/site-packages/requests/adapters.py\", line 667, in send",
   "    resp = conn.urlopen(",
   "           ^^^^^^^^^^^^^",
   "  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 801, in urlopen",
   "    retries = retries.increment(",
   "              ^^^^^^^^^^^^^^^^^^",
   "  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.11/site-packages/urllib3/util/retry.py\", line 552, in increment",
   "    raise six.reraise(type(error), error, _stacktrace)",
   "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^",
   "  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.11/site-packages/urllib3/packages/six.py\", line 769, in reraise",
   "    raise value.with_traceback(tb)",
   "  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 715, in urlopen",
   "    httplib_response = self._make_request(",
   "                       ^^^^^^^^^^^^^^^^^^^",
   "  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 467, in _make_request",
   "    six.raise_from(e, None)",
   "  File \"<string>\", line 3, in raise_from",
   "  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 462, in _make_request",
   "    httplib_response = conn.getresponse()",
   "                       ^^^^^^^^^^^^^^^^^^",
   "  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.11/http/client.py\", line 1395, in getresponse",
   "    response.begin()",
   "  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.11/http/client.py\", line 325, in begin",
   "    version, status, reason = self._read_status()",
   "                              ^^^^^^^^^^^^^^^^^^^",
   "  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.11/http/client.py\", line 294, in _read_status",
   "    raise RemoteDisconnected(\"Remote end closed connection without\"",
   "urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))",
   "",
   "During handling of the above exception, another exception occurred:",
   "",
   "Traceback (most recent call last):",
   "  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.11/site-packages/github3/models.py\", line 201, in _request",
   "    return request_method(*args, **kwargs)",
   "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^",
   "  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/git_utils.py\", line 754, in get",
   "    return self._forward_request(self._session.get, *args, **kwargs)",
   "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^",
   "  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/git_utils.py\", line 746, in _forward_request",
   "    response = method(*args, **kwargs)",
   "               ^^^^^^^^^^^^^^^^^^^^^^^",
   "  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.11/site-packages/requests/sessions.py\", line 602, in get",
   "    return self.request(\"GET\", url, **kwargs)",
   "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^",
   "  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.11/site-packages/github3/session.py\", line 171, in request",
   "    response = super().request(*args, **kwargs)",
   "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^",
   "  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.11/site-packages/requests/sessions.py\", line 589, in request",
   "    resp = self.send(prep, **send_kwargs)",
   "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^",
   "  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.11/site-packages/requests/sessions.py\", line 703, in send",
   "    r = adapter.send(request, **kwargs)",
   "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^",
   "  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.11/site-packages/requests/adapters.py\", line 682, in send",
   "    raise ConnectionError(err, request=request)",
   "requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))",
   "",
   "During handling of the above exception, another exception occurred:",
   "",
   "Traceback (most recent call last):",
   "  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py\", line 744, in _run_migrator_on_feedstock_branch",
   "    migrator_uid, pr_json = run_with_tmpdir(",
   "                            ^^^^^^^^^^^^^^^^",
   "  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py\", line 451, in run_with_tmpdir",
   "    return run(",
   "           ^^^^",
   "  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py\", line 523, in run",
   "    if not _prepare_feedstock_repository(",
   "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^",
   "  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py\", line 165, in _prepare_feedstock_repository",
   "    backend.fork(context.git_repo_owner, context.git_repo_name)",
   "  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.11/contextlib.py\", line 81, in inner",
   "    return func(*args, **kwds)",
   "           ^^^^^^^^^^^^^^^^^^^",
   "  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/git_utils.py\", line 844, in fork",
   "    if self.does_repository_exist(self.user, repo_name):",
   "       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^",
   "  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/git_utils.py\", line 820, in does_repository_exist",
   "    self._get_repo(owner, repo_name)",
   "  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/git_utils.py\", line 814, in _get_repo",
   "    raise e",
   "  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/git_utils.py\", line 804, in _get_repo",
   "    repo = self.github3_client.repository(owner, repo_name)",
   "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^",
   "  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.11/site-packages/github3/github.py\", line 2103, in repository",
   "    json = self._json(self._get(url), 200)",
   "                      ^^^^^^^^^^^^^^",
   "  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.11/site-packages/github3/models.py\", line 216, in _get",
   "    return self._request(\"get\", url, **kwargs)",
   "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^",
   "  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.11/site-packages/github3/models.py\", line 206, in _request",
   "    raise exceptions.ConnectionError(exc)",
   "github3.exceptions.ConnectionError: <class 'requests.exceptions.ConnectionError'>: A connection-level exception occurred: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))",
   ""
  ]
 },
 "pinning_version": "2024.12.05.14.45.32",
 "pre_pr_migrator_attempts": {},
 "pre_pr_migrator_status": {},
 "smithy_version": "3.44.9"
}